### PR TITLE
symbiotic: Print sys.argv contents to the standard output in debug mode

### PR DESCRIPTION
**Pull request by lzaoral**
This is very useful for automated processing of the results so that users
know how to reproduce it afterwards from the report itself.

### CODE REVIEW

**Review by mchalupa — COMMENTED** [review]
Hmm, and do we want to print it to stdout always or just when `--debug` is specified?

**Comment by kdudka** [comment]
I think the information is always useful.  valgrind also prints it by default.  We run Symbiotic automatically on test-suites embedded in RPM packages.  Now we get stack traces over the source code without any information about how the process was executed initially, namely which binary (or bitcode) was executed, and which parameters were given to it.  Ideally we would like to get output like this out of Symbiotic:
```sh
Error: VALGRIND_WARNING:
logrotate-3.18.0/build/logrotate: note: while executing process 10931 with arguments: -v -m ./mailer -s state test-config.18 -l syslog --force
logrotate-3.18.0/build/../logrotate.c:2983: warning[Leak_DefinitelyLost]: 13 bytes in 2 blocks are definitely lost in loss record 6 of 14
/usr/lib64/libpopt.so.0.0.1: note: called from poptGetNextOpt()
logrotate-3.18.0/build/../logrotate.c:2983: note: called from main()
# 2981|       poptSetOtherOptionHelp(optCon, "[OPTION...] <configfile>");
# 2982|   
# 2983|->     while ((arg = poptGetNextOpt(optCon)) >= 0) {
# 2984|           switch (arg) {
# 2985|               case 'd':
```

We are converting Symbiotic's output to something very close to it but the mentioned piece of information is still missing.

**Comment by mchalupa** [comment]
I agree that this bit of information is useful for automated processing, but I am not sure the user is interested in seeing the used command again when Symbiotic is run manually. If Symbiotic dumps the information only with debugging enabled, all you need to do is to run Symbiotic with debugging enabled to get this piece of information, don't you?

**Comment by kdudka** [comment]
I am not sure what the other consequences are if we enable Symbiotic debugging.  I would expect the debugging mode to be useful mainly for developers of Symbiotic but have not looked at what it really does.

**Comment by lzaoral** [comment]
I've just tried to execute `aufover-benchmark` with `--debug=all` and `symbiotic`'s output was parsed and converted without any issues. I'll change the message to be part of the debug output as @mchalupa suggested.

**Comment by mchalupa** [comment]
If there would be a problem with `--debug=all`, you can add `domain="XXX"` to the `dbg` function and then call Symbiotic with `--debug=XXX` to filter the output.

Alternatively, we could adjust the `--report` switch, which does not do much at the moment... After all, one of the main motivations for that switch was to change the form of the output in situations like this.

**Comment by lzaoral** [comment]
Thank you for the suggestions, @mchalupa. If there will be a problem, I'll let you know or make a new PR. I'd merge this PR as it is, though.

**Pull request merged**
