### PR TITLE
use env in shebangs to support non-stanard python interpret locations

### PR DESCRIPTION
**Pull request by MichalHe**
While I on my adventure to learn more about symbiotic, I have noticed #232 , so I went ahead and fixed it.

I have noticed that the same pattern is repeated in other symbiotic files as well. However, after skimming trough these files I have noticed that none of them are  executable, or IMHO not meant to  be executed, and therefore the shebang usage can be considered as misleading. If such a case that a consensus will be reach to drop the shebangs, I have no problem of doing it as a part of this PR.

### CODE REVIEW

**Review by kdudka — APPROVED** [review]

**Review by lzaoral — CHANGES_REQUESTED** [review]
Thanks a lot, @MichalHe! Could you also change the shebangs to point to `python3`? Some systems do not provide unversioned Python by default. Also, please add `Fixes: #232` clause to the commit message.

**Comment by MichalHe** [comment]
@lzaoral done

**Review by lzaoral — APPROVED** [review]

**Comment by lzaoral** [comment]
@MichalHe #235 was merged, could you please rebase this PR? Thanks a lot!

**Comment by MichalHe** [comment]
@lzaoral done

**Comment by lzaoral** [comment]
Thank you for your contribution, @MichalHe!

**Pull request merged**
