### PR TITLE
Migrate to GitHub Actions + Add a new test runner

### PR DESCRIPTION
**Pull request by lzaoral**
This is just a draft because:
- staticafi/klee is not yet compatible with LLVM 11 and newer (#187),
- some tests fail with unexpected results or just crash on `assert`'s.

The CI is run with LLVM 8-10 only at the moment but that should be enough to spot and fix the major bugs as there is quite a lot of them (see the CI logs).

edit: typo

### CODE REVIEW

**Comment by lzaoral** [comment]
The results are here: https://github.com/lzaoral/symbiotic/actions/runs/1044696822

**Comment by lzaoral** [comment]
Improvements to consider:
- [ ]  Do not strip binaries so that stack traces in CI remain useful.
- [ ] Add jobs with sanitizers.

**Comment by lzaoral** [comment]
I've managed to add ASAN and UBSAN jobs without binary stripping and the outputs are here: https://github.com/lzaoral/symbiotic/actions/runs/1060235757

**Comment by lzaoral** [comment]
Alright, this one should be the right output: https://github.com/lzaoral/symbiotic/runs/3145330931?check_suite_focus=true

**Comment by lzaoral** [comment]
I've updated the PR with two changes:
* `clang`'s sanitizers require the `llvm-symbolizer` tool in `PATH` so that they can produce useful stack traces. That was not the case in our CI as only `llvm-symbolizer-X` was present there.
* Add LLVM 7.1 job and use LLVM 7.1 release from LLVM instead of LLVM 7.0 from Ubuntu repositories. LLVM 7.0 built with GCC is ABI incompatible with our tools built with `clang`. Unfortunately, the fixed release never made it to the official Ubuntu repos.

**Comment by lzaoral** [comment]
* Fix compilation with LLVM 6 and add a corresponding job.

**Review by mchalupa — APPROVED** [review]
Thanks!

**Pull request merged**
